CREATE TABLE ITEM (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE INT NOT NULL
);
CREATE TABLE INVENTORY (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_ID INT NOT NULL,
    QTY INT NOT NULL,
    TYPE VARCHAR(1) NOT NULL
);
CREATE TABLE ORDER_SEQ
(
  id INT PRIMARY KEY
);
CREATE TABLE "order" (
    ORDER_NO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_ID INT NOT NULL,
    QTY INT NOT NULL,
    PRICE INT NOT NULL
);

INSERT INTO ITEM (NAME, PRICE) VALUES ('Pen', 5);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Book', 10);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Bag', 30);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Pencil', 3);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Shoe', 45);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Box', 5);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Cap', 25);

INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (1, 5, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (2, 10, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (3, 30, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (4, 3, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (5, 45, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (6, 5, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (7, 25, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (4, 7, 'T');
INSERT INTO INVENTORY (ITEM_ID, QTY, TYPE) VALUES (5, 10, 'W');

INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (1, 2, 5);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (2, 3, 10);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (5, 4, 45);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (4, 1, 2);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (5, 2, 45);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (6, 3, 5);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (1, 5, 5);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (2, 4, 10);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (3, 2, 30);
INSERT INTO "order" (ITEM_ID, QTY, PRICE) VALUES (4, 3, 3);
